#!/bin/bash
# Lantrn Agent Builder - Start Script for Mac Ultra + NAS Deployment
# Optimized for Apple Silicon (ARM64)

set -e

# ============================================
# Configuration
# ============================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.yml"
ENV_FILE="$PROJECT_DIR/.env"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ============================================
# Helper Functions
# ============================================
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -\e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}$1${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

check_command() {
    if ! command -v "$1" &> /dev/null; then
        log_error "$1 is not installed. Please install it first."
        return 1
    fi
    return 0
}

check_port() {
    local port=$1
    if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1; then
        return 0  # Port is in use
    fi
    return 1  # Port is free
}

wait_for_service() {
    local url=$1
    local name=$2
    local max_retries=${3:-30}
    local retry_count=0
    
    log_info "Waiting for $name to be ready..."
    while [ $retry_count -lt $max_retries ]; do
        if curl -s -f "$url" > /dev/null 2>&1; then
            log_success "$name is ready!"
            return 0
        fi
        retry_count=$((retry_count + 1))
        echo -n "."
        sleep 2
    done
    echo ""
    log_error "$name did not become ready in time"
    return 1
}

# ============================================
# Startup Banner
# ============================================
echo ""
echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║                                                              ║${NC}"
echo -e "${BOLD}${CYAN}║           🏮 LANTRN AGENT BUILDER - STARTUP                  ║${NC}"
echo -e "${BOLD}${CYAN}║           Mac Ultra + NAS Deployment                         ║${NC}"
echo -e "${BOLD}${CYAN}║                                                              ║${NC}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# ============================================
# Pre-flight Checks
# ============================================
log_step "🔍 Running Pre-flight Checks"

# Check architecture
ARCH=$(uname -m)
log_info "System architecture: $ARCH"
if [ "$ARCH" != "arm64" ]; then
    log_warning "This script is optimized for ARM64 (Apple Silicon). Current: $ARCH"
fi

# Check Docker
if ! check_command docker; then
    log_error "Docker is required but not installed."
    log_info "Install with: brew install --cask docker"
    exit 1
fi
log_success "Docker is installed: $(docker --version)"

# Check Docker Compose
if ! docker compose version &> /dev/null; then
    log_error "Docker Compose is required but not available."
    exit 1
fi
log_success "Docker Compose is available: $(docker compose version --short)"

# Check if Docker daemon is running
if ! docker info &> /dev/null; then
    log_error "Docker daemon is not running. Please start Docker Desktop."
    exit 1
fi
log_success "Docker daemon is running"

# ============================================
# Environment Configuration
# ============================================
log_step "⚙️  Configuring Environment"

# Create .env file if it doesn't exist
if [ ! -f "$ENV_FILE" ]; then
    log_info "Creating default .env file..."
    cat > "$ENV_FILE" << 'ENV'
# Lantrn Agent Builder - Environment Configuration
# Generated by start.sh

# Environment
ENV=production
LOG_LEVEL=INFO

# Model Configuration
DEFAULT_MODEL=llama3.2:3b
FAST_MODEL=llama3.2:3b
HQ_MODEL=llama3.1:70b

# API Security (change these!)
API_KEY=
SECRET_KEY=

# NAS Paths (uncomment and configure for your setup)
# NAS_PATH=/Volumes/NAS/lantrn
# OLLAMA_NAS_PATH=/Volumes/NAS/ollama/models
ENV
    log_success "Created .env file at $ENV_FILE"
    log_warning "Please review and update $ENV_FILE with your configuration"
else
    log_success "Using existing .env file"
fi

# Load environment
set -a
source "$ENV_FILE"
set +a

# ============================================
# NAS Mount Check (Optional)
# ============================================
log_step "💾 Checking Storage Configuration"

if [ -n "$NAS_PATH" ]; then
    if [ -d "$NAS_PATH" ]; then
        log_success "NAS mount found at $NAS_PATH"
        # Create directories if needed
        mkdir -p "$NAS_PATH/data" "$NAS_PATH/logs" "$NAS_PATH/models"
    else
        log_warning "NAS path configured but not found: $NAS_PATH"
        log_warning "Continuing with local storage..."
    fi
else
    log_info "Using local Docker volumes for storage"
fi

# ============================================
# Port Availability Check
# ============================================
log_step "🔌 Checking Port Availability"

PORTS=(8000 11434 8001)
PORT_NAMES=("API" "Ollama" "ChromaDB")

for i in "${!PORTS[@]}"; do
    PORT=${PORTS[$i]}
    NAME=${PORT_NAMES[$i]}
    if check_port $PORT; then
        log_warning "Port $PORT ($NAME) is already in use"
        log_info "Checking if it's our container..."
        if docker ps --format '{{.Names}}' | grep -q "lantrn"; then
            log_info "Lantrn containers are already running"
        else
            log_error "Port $PORT is used by another process. Stop it or change the port."
            lsof -i :$PORT
        fi
    else
        log_success "Port $PORT ($NAME) is available"
    fi
done

# ============================================
# Ollama Setup (Local or Docker)
# ============================================
log_step "🦙 Configuring Ollama"

# Check if local Ollama is running
if curl -s -f http://localhost:11434/api/tags > /dev/null 2>&1; then
    log_success "Local Ollama is running on port 11434"
    OLLAMA_MODE="local"
    
    # List available models
    log_info "Available models:"
    curl -s http://localhost:11434/api/tags | python3 -c "
import sys, json
try:
    models = json.load(sys.stdin).get('models', [])
    for m in models:
        print(f'  - {m[\"name\"]} ({m.get(\"size\", \"unknown\")})')
except:
    print('  Could not list models')
" 2>/dev/null || log_warning "Could not list Ollama models"
    
    # Pull default models if not present
    for MODEL in "llama3.2:3b" "llama3.1:70b"; do
        if ! curl -s http://localhost:11434/api/tags | grep -q "$MODEL"; then
            log_info "Pulling model: $MODEL"
            ollama pull "$MODEL" || log_warning "Could not pull $MODEL"
        fi
    done
else
    log_info "Local Ollama not found. Will use Docker Ollama service."
    OLLAMA_MODE="docker"
fi

# ============================================
# Build and Start Services
# ============================================
log_step "🚀 Starting Services"

cd "$PROJECT_DIR"

# Pull required images
log_info "Pulling required Docker images..."
docker compose pull 2>/dev/null || true

# Build the application image
log_info "Building Lantrn Agent image..."
docker compose build --no-cache lantrn-api 2>&1 | tail -20

# Start services
log_info "Starting Docker Compose services..."

if [ "$OLLAMA_MODE" = "local" ]; then
    # Start without Ollama container if local Ollama is available
    log_info "Using local Ollama, starting API and ChromaDB only..."
    docker compose up -d lantrn-api chromadb
else
    # Start all services including Ollama
    log_info "Starting all services (including Ollama)..."
    docker compose up -d
fi

# ============================================
# Health Checks
# ============================================
log_step "🏥 Running Health Checks"

# Wait for services to be ready
log_info "Waiting for services to start (this may take a minute)..."
sleep 10

# Check ChromaDB
if wait_for_service "http://localhost:8001/api/v1/heartbeat" "ChromaDB" 30; then
    log_success "ChromaDB is healthy"
else
    log_warning "ChromaDB health check failed"
fi

# Check Ollama
if [ "$OLLAMA_MODE" = "docker" ]; then
    if wait_for_service "http://localhost:11434/api/tags" "Ollama" 60; then
        log_success "Ollama is healthy"
        
        # Pull default models
        log_info "Pulling default models (this may take a while)..."
        docker exec lantrn-ollama ollama pull llama3.2:3b &
        docker exec lantrn-ollama ollama pull llama3.1:70b &
        wait
    else
        log_warning "Ollama health check failed"
    fi
fi

# Check API
if wait_for_service "http://localhost:8000/" "Lantrn API" 60; then
    log_success "Lantrn API is healthy"
else
    log_error "API health check failed"
    log_info "Check logs with: docker compose logs lantrn-api"
fi

# ============================================
# Display Status
# ============================================
log_step "📊 Service Status"

docker compose ps

# ============================================
# Display Access Information
# ============================================
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║                                                              ║${NC}"
echo -e "${BOLD}${GREEN}║           ✅ LANTRN AGENT BUILDER IS RUNNING!                ║${NC}"
echo -e "${BOLD}${GREEN}║                                                              ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BOLD}Access Points:${NC}"
echo -e "  🌐 API:           ${CYAN}http://localhost:8000${NC}"
echo -e "  📊 API Docs:      ${CYAN}http://localhost:8000/docs${NC}"
echo -e "  🦙 Ollama API:    ${CYAN}http://localhost:11434${NC}"
echo -e "  🔍 ChromaDB:      ${CYAN}http://localhost:8001${NC}"
echo ""
echo -e "${BOLD}Useful Commands:${NC}"
echo -e "  📋 View logs:     ${CYAN}docker compose logs -f${NC}"
echo -e "  🛑 Stop services: ${CYAN}./scripts/stop.sh${NC}"
echo -e "  🔄 Restart:       ${CYAN}docker compose restart${NC}"
echo -e "  📊 Status:        ${CYAN}docker compose ps${NC}"
echo ""
